name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
    types: [closed]
jobs:
  push_to_production:
    runs-on: self-hosted
    steps:
      - run: git -C /var/www/tymon.wilczek.dev/szkola pull
